language: php
sudo: false
php: 7.2
script:
    - phpenv config-rm xdebug.ini || return 0

after_script:
    - |
        if [[ $TRAVIS_BRANCH == "master" ]]; then
            cd ../../
            composer require apigen/apigen --dev
            composer require roave/better-reflection --dev

            mkdir ./docs/
            mkdir ./development/

            cd development/
            git clone https://${GH_TOKEN}@github.com/$TRAVIS_REPO_SLUG.git
            cd wponion/
            git checkout development
            cd ../../

            echo "Master Generator";
            vendor/bin/apigen generate -s $TRAVIS_REPO_SLUG/ --destination ./docs/
            
            echo "Development Generator";
            mkdir ./docs_2/
            mkdir ./docs_2/development/
            vendor/bin/apigen generate -s development/wponion/ --destination ./docs_2/development/ --debug
            mv ./docs_2/ ./docs/
            cd docs/
            git init
            git remote add origin https://${GH_TOKEN}@github.com/$TRAVIS_REPO_SLUG.git
            git config --global user.email "travis@travis-ci.org"
            git config --global user.name "Travis"
            git add .
            git commit -m "API Regenerated"
            git push origin master:gh-pages -f
        fi
        
notifications:
email: never
