language: php
sudo: false
php: 7.1
script:
    - phpenv config-rm xdebug.ini || return 0

after_script:
    - |
        if [[ $TRAVIS_BRANCH == "master" ]]; then
          cd ../../
          composer require apigen/apigen --dev
          mkdir ./docs/
          vendor/bin/apigen generate -s $TRAVIS_REPO_SLUG/ --destination ./docs/
          
          mkdir ./development/
          ls
          cd development/
          git clone https://${GH_TOKEN}@github.com/$TRAVIS_REPO_SLUG.git
          cd wponion/
          git checkout development
          ls
          cd ../../
          mkdir ./docs/development/
          vendor/bin/apigen generate -s ./development/wponion/ --destination ./docs/development/
          
          cd docs/
            git init
            git remote add origin https://${GH_TOKEN}@github.com/$TRAVIS_REPO_SLUG.git
            git config --global user.email "travis@travis-ci.org"
            git config --global user.name "Travis"
            git add .
            git commit -m "API Regenerated"
            git push origin master:gh-pages -f
        fi
        
notifications:
email: never
