language: php
sudo: false
php: 7.1
script:
    - phpenv config-rm xdebug.ini || return 0

after_script:
    - |
        if [[ $TRAVIS_BRANCH == "master" ]]; then
          cd ../../
          composer require apigen/apigen --dev
          mkdir ./docs/
          ../../vendor/bin/apigen generate -s ../../$TRAVIS_REPO_SLUG/ --destination ./docs/
          
          mkdir ./development/
          ls
          cd development/
          git clone https://github.com/wponion/wponion.git
          cd wponion/
          ls
        fi
        
notifications:
email: never
