name: New Release

on:
  push:
    branches:
    - refs/tags/*

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checking Out WPOnion Data
      uses: actions/checkout@v1
    - name: Setting Up Composer
      uses: pxgamer/composer-action@master
      with: 
        command: install --no-dev
    - name: WordPress Plugin Deploy
      uses: varunsridharan/action-wp-org-deploy@master
      with:
        WORDPRESS_PASSWORD: ${{ secrets.WP_PASSWORD }}
        WORDPRESS_USERNAME: ${{ secrets.WP_USERNAME }}
        SLUG: wponion
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
